// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqClR9DmJEjq9gUlERnGTfaH2dZ-zN00',
    appId: '1:431192941742:web:344fde02b324afb6dab93f',
    messagingSenderId: '431192941742',
    projectId: 'demomessage-2d1ea',
    authDomain: 'demomessage-2d1ea.firebaseapp.com',
    storageBucket: 'demomessage-2d1ea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoEr5u9BVZNTHJc66al_qTpmHbJj-fYDs',
    appId: '1:431192941742:android:a268a5038684a569dab93f',
    messagingSenderId: '431192941742',
    projectId: 'demomessage-2d1ea',
    storageBucket: 'demomessage-2d1ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeN9oBLAkFk8jGXhaJvNyBhuLKr28ytAo',
    appId: '1:431192941742:ios:5b79416c16331c92dab93f',
    messagingSenderId: '431192941742',
    projectId: 'demomessage-2d1ea',
    storageBucket: 'demomessage-2d1ea.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeN9oBLAkFk8jGXhaJvNyBhuLKr28ytAo',
    appId: '1:431192941742:ios:5b79416c16331c92dab93f',
    messagingSenderId: '431192941742',
    projectId: 'demomessage-2d1ea',
    storageBucket: 'demomessage-2d1ea.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkqClR9DmJEjq9gUlERnGTfaH2dZ-zN00',
    appId: '1:431192941742:web:b52cd8505470bbc2dab93f',
    messagingSenderId: '431192941742',
    projectId: 'demomessage-2d1ea',
    authDomain: 'demomessage-2d1ea.firebaseapp.com',
    storageBucket: 'demomessage-2d1ea.appspot.com',
  );
}
